"use client";

import Link from "next/link";
import { useLang } from "./LangContext";
import { SITE } from "@/lib/constants";

export function Footer() {
  const { lang } = useLang();
  return (
    <footer className="mt-16 border-t border-ink-200/70 dark:border-ink-800/70">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 grid sm:grid-cols-3 gap-6 text-xs text-ink-600 dark:text-ink-300">
        <div>
          <div className="flex items-center gap-2 font-bold text-base text-ink-900 dark:text-ink-100">
            <span className="inline-block w-5 h-5 rounded fire-gradient" aria-hidden />
            {SITE.name}
          </div>
          <p className="mt-2 text-ink-500 dark:text-ink-400">
            {lang === "zh"
              ? "聚合 + AI 摘要的 AI 行业每日热度榜。"
              : "Aggregated + AI-summarised daily AI pulse."}
          </p>
        </div>
        <div>
          <div className="font-semibold text-ink-700 dark:text-ink-200">
            {lang === "zh" ? "浏览" : "Browse"}
          </div>
          <ul className="mt-2 space-y-1">
            <li><Link href="/" className="hover:text-accent">{lang === "zh" ? "热度榜" : "Hot list"}</Link></li>
            <li><Link href="/digest" className="hover:text-accent">{lang === "zh" ? "今日简报" : "Today's brief"}</Link></li>
            <li><Link href="/search" className="hover:text-accent">{lang === "zh" ? "搜索" : "Search"}</Link></li>
            <li><a href="/feed.xml" className="hover:text-accent">RSS</a></li>
          </ul>
        </div>
        <div>
          <div className="font-semibold text-ink-700 dark:text-ink-200">
            {lang === "zh" ? "数据" : "Data"}
          </div>
          <p className="mt-2 text-ink-500 dark:text-ink-400 leading-relaxed">
            {lang === "zh"
              ? "数据聚合自公开 RSS、HuggingFace、GitHub 等。摘要 / 简报由 Claude 自动生成,可能存在错误,请以原文为准。"
              : "Aggregated from public RSS, HuggingFace, GitHub and more. Summaries are AI-generated by Claude — always check the source link."}
          </p>
        </div>
      </div>
      <div className="border-t border-ink-200/70 dark:border-ink-800/70">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-3 text-[11px] text-ink-500 dark:text-ink-400 flex flex-wrap gap-3 justify-between">
          <span>© {new Date().getFullYear()} {SITE.name}</span>
          <span>{lang === "zh" ? "由 Claude · Next.js · Prisma 强力驱动" : "Powered by Claude · Next.js · Prisma"}</span>
        </div>
      </div>
    </footer>
  );
}
